theme = "nord-night"

[editor]
line-number = "relative"
completion-replace = true
trim-trailing-whitespace = true
end-of-line-diagnostics = "hint"
color-modes = true
true-color = true

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.auto-save]
after-delay.enable = true
after-delay.timeout = 3000

[editor.indent-guides]
render = true
skip-levels = 1

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'

[editor.statusline]
left = [
  "mode",
  "spinner",
  "version-control",
  "spacer",
  "separator",
  "file-name",
  "read-only-indicator",
  "file-modification-indicator",
]
right = [
  "diagnostics",
  "workspace-diagnostics",
  "position",
  "total-line-numbers",
  "position-percentage",
  "file-encoding",
  "file-line-ending",
  "file-type",
  "register",
  "selections",
]
separator = "|"

# ===================
# === Normal Mode ===
# ===================
[keys.normal]
0 = "goto_line_start"
"$" = "goto_line_end"
G = "goto_file_end"
# removes everything to the right of the cursor
D = ["ensure_selections_forward", "extend_to_line_end", "delete_selection"]
# enter select mode and mark line
V = ["select_mode", "extend_to_line_bounds"]
esc = ["collapse_selection", "keep_primary_selection"]
ret = "add_newline_above"
"Cmd-ret" = "add_newline_below"

[keys.normal.space]
q = ":quit"

[keys.normal."="] # minor mode formatting
f = ":format"
w = ":set whitespace.render all"
W = ":set whitespace.render none"
s = ":toggle soft-wrap.enable"
r = ":set rulers [120]"
R = ":set rulers [0]"

[keys.normal.space.f] # minor mode file
f = "file_picker_in_current_directory"
F = "file_picker"
p = "file_picker_in_current_buffer_directory"
P = "buffer_picker"
w = ":write"
c = ":bc"
x = ":bco"
l = ":toggle lsp.display-inlay-hints"
"." = ":toggle file-picker.hidden"
r = ":reload-all"
z = ":reset-diff-change"
b = ":echo %sh{git blame -L %{cursor_line},+1 %{buffer_name}}"
d  = [":vsplit-new", ":lang diff", ":insert-output git diff"]

[keys.normal.space.w]
# create key cluster of j,i,k,l
h = "hsplit"
j = "jump_view_left"
i = "jump_view_up"
k = "jump_view_down"
J = "swap_view_left"
I = "swap_view_up"
K = "swap_view_down"

# ===================
# === Select Mode ===
# ===================
[keys.select]
0 = "goto_line_start"
"$" = "goto_line_end"
G = "extend_to_file_end"
