
[[language]]
name = "go"
language-servers = ["gopls", "harper-ls"]
auto-format = true
formatter = { command = "gofmt" }

[[language]]
name = "yaml"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "yaml"] }

[language-server.rumdl]
command = "rumdl"
args = ["server"]

[[language]]
name = "markdown"
language-servers = ["marksman", "harper-ls"]
